### ISSUE TITLE
Use a multi stage build to make the docker image smaller

### ISSUE THREAD

**Issue by gpbenton** [gpbenton/engMQTTClient#27]

**Comment by setdetnet** [comment]
> _No description provided._
Graham, I can for sure mod my Docker file to use Multi Stage Build. However, the reality is:
- There are four phases of the current build.
- Phase 1 is log4c build from sources.  This could be reduced down by removing sources after build.
- Phase 2 is mosquito package install. This cannot be reduced down.
- Phase 3 is your engmqtt client/broker. This could be reduced down by removing sources after build.
- Phase 4 executable.
- The removal of log4c and your engmqtt sources is not going to make any noticeable difference to the net resultant image.

The Dockerfile already is multi-stage, it utilises the **FROM** and **RUN** directives. A dev environment using **gcc** is created as an intermediate image. The final image for RUN contains this env and the sources. What could be applied in order to reduce image size, is to remove this build image from the final image, viz:-

- Phase1: 
Create intermediate image#1 using FROM gcc (build environment).
- Phase2: 
Build log4c.
Install mosquito files from package repo.
Build engmqtt.
- Phase3: 
Create intermediate image#2 and **COPY --from**  image#1 all distributable files. This will remove gcc, source code and build env files. 
- Phase4: 
RUN the client. Intermediate images will be removed and size reduced.

Is this what you mean?

**Comment by gpbenton** [comment]
That is exactly what I mean.  It should be straightforward, I just haven't had a free weekend to try it out.

**Comment by gpbenton** [comment]
New image released as gpbenton/engmqttclient:2.0.0.   81.6MB as opposed to 872MB.
Added some example to the docker-compose on how to add debug.
